name: Generate ASCII Artwork

on: push

jobs:
  generate_ascii_artwork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Executing shell script
        run: ./ASCII-script.sh

     

 
